logging:
  config: classpath:log4j2.xml
netty:
  port: 9000
spring:
  redis:
    host: redis
    database: 1
    port: 6379
    password: 123456
  data:
    mongodb:
      host: mongo
      database: im