logging:
  config: classpath:log4j2.xml
netty:
  port: 9000
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password: 123456
  data:
    mongodb:
      host: localhost
      database: im
  main:
    web-application-type: none
message:
  host: message
  port: 8080