logging:
  config: classpath:log4j2.xml
netty:
  port: 9000
hbase:
  zookeeper:
    quorum: localhost
    property:
      clientPort: 49158
spring:
  redis:
    host: 8.134.34.84
    database: 1
    port: 6379
    password: 123456