logging:
  config: classpath:log4j2.xml
netty:
  port: 9999
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password: 123456
  data:
    mongodb:
      host: localhost
      database: im
      port: 49154