logging:
  config: classpath:log4j2.xml
netty:
  port: 9999
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password: 123456
  data:
    mongodb:
      host: localhost
      database: im
message:
  host: localhost
  port: 8080
redisson:
  singleServerConfig:
    address: localhost:6379